import projectImg from '../src/assets/project.jpg';
import carGurus from '../src/assets/project/carGurus.webp';
import dantistImg from '../src/assets/project/dantistImg.jpg';
import trainLang from '../src/assets/project/trainLanguageImg.png';
export const navigation = [
  {
    name: 'home',
    href: 'home',
  },
  {
    name: 'about',
    href: 'about',
  },
  {
    name: 'skills',
    href: 'skills',
  },
  {
    name: 'portfolio',
    href: 'portfolio',
  },
  // {
  //   name: 'services',
  //   href: 'services',
  // },
  // {
  //   name: 'testimonials',
  //   href: 'testimonials',
  // },
  {
    name: 'contact',
    href: 'contact',
  },
];

// projects
export const projectsNav = [
  {
    name: 'all',
  },
  {
    name: 'React/node js',
  },
  {
    name: 'React',
  },
  {
    name: 'JS/API',
  },
  {
    name: 'UI/UX Design',
  },
];

export const projectsData = [
  {
    id: 1,
    image: carGurus,
    name: 'Car Gurus',
    des: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id iure ullam ex commodi voluptas excepturi inventore molestias sint dignissimos ratione?',
    category: 'React/node js',
    repo_link:
      'https://github.com/imran-mridha/car-gurus-client',
    server_link: 'https://github.com/DiptaPal/bd-store-dot-com-server-side',
    live_link: 'https://car-gurus-bd.web.app/',
    technology: [
      'React',
      'Node.JS',
      'Firebase',
      'Mongodb',
      'Authentication',
      'React-Query',
      'Axios',
      'Swiper JS',
      'React Hooks Form',
      'Express Js',
      'Date Fns',
      'JWT',
      'Tailwind',
      'Daisy UI',
      'Social Login',
    ],
    tag: 'NEW',
  },
  {
    id: 2,
    image: dantistImg,
    name: 'Smile Builders',
    des: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id iure ullam ex commodi voluptas excepturi inventore molestias sint dignissimos ratione?',
    category: 'React/node js',
    repo_link: 'https://github.com/imran-mridha/smile-builders-client',
    server_link: 'https://github.com/DiptaPal/doctors-protal-server',
    live_link: 'https://smile-builders-24d63.web.app/',
    technology: [
      'React',
      'Node.JS',
      'Firebase',
      'Mongodb',
      'Authentication',
      'React-Query',
      'React Hooks Form',
      'Express Js',
      'Date Fns',
      'Day Piker',
      'JWT',
      'Tailwind',
      'Daisy UI',
      'Social Login',
    ],
    tag: 'NEW',
  },
  {
    id: 3,
    image: trainLang,
    name: 'Train Language',
    des: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id iure ullam ex commodi voluptas excepturi inventore molestias sint dignissimos ratione?',
    category: 'React/node js',
    repo_link: 'https://github.com/imran-mridha/train-language-client',
    server_link: 'https://github.com/DiptaPal/bengali-taste-server',
    live_link: 'https://train-language.web.app/',
    technology: [
      'React',
      'Node.JS',
      'Firebase',
      'Mongodb',
      'Authentication',
      'Express Js',
      'Date Fns',
      'JWT',
      'Tailwind',
      'React Toastify',
      'React Icon',
      'Swiper JS',
      'React-loader-spinner',
      'React Aos',
      'React countup',
      'React-photo-view',
      'Social Login',
    ],
    tag: '1 month ago',
  },
  {
    id: 4,
    image: projectImg,
    name: 'Volunteer Network',
    des: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id iure ullam ex commodi voluptas excepturi inventore molestias sint dignissimos ratione?',
    category: 'React/node js',
    repo_link: 'https://github.com/DiptaPal/volunteer-network-client',
    server_link: 'https://github.com/DiptaPal/volunteer-network-server',
    live_link: 'https://volunteer-network-9ff29.web.app/',
    technology: [
      'React',
      'Node.JS',
      'Firebase',
      'Mongodb',
      'Authentication',
      'Express Js',
      'JWT',
      'Tailwind',
      'React Toastify',
      'React Icon',
      'Social Login',
    ],
    tag: '1 month ago',
  },
  {
    id: 5,
    image: projectImg,
    name: 'Genius Car',
    des: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id iure ullam ex commodi voluptas excepturi inventore molestias sint dignissimos ratione?',
    category: 'React/node js',
    repo_link: 'https://github.com/DiptaPal/online-tuition-client-side',
    server_link: 'https://github.com/DiptaPal/onine-tuition-server-side',
    live_link: 'https://genius-car-90893.web.app/',
    technology: [
      'React',
      'Node.JS',
      'Firebase',
      'Mongodb',
      'Authentication',
      'Express Js',
      'JWT',
      'Tailwind',
      'React Toastify',
      'React Icon',
      'Social Login',
    ],
    tag: '1 month ago',
  },
  {
    id: 6,
    image: projectImg,
    name: 'Ema John',
    des: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id iure ullam ex commodi voluptas excepturi inventore molestias sint dignissimos ratione?',
    category: 'React/node.js',
    repo_link: 'https://github.com/DiptaPal/ema-john-server',
    server_link: 'https://github.com/DiptaPal/ema-john-pagination',
    live_link: 'https://ema-john-simple-d1c22.web.app/',
    technology: [
      'React',
      'Node.JS',
      'Firebase',
      'Mongodb',
      'Authentication',
      'Express Js',
      'JWT',
      'Tailwind',
      'React Toastify',
      'React Icon',
      'Social Login',
    ],
    tag: '2 month ago',
  },
  {
    id: 7,
    image: projectImg,
    name: 'Online Study',
    des: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id iure ullam ex commodi voluptas excepturi inventore molestias sint dignissimos ratione?',
    category: 'React',
    repo_link: 'https://github.com/DiptaPal/genius-car-client',
    server_link: 'https://github.com/DiptaPal/genius-car-server',
    live_link: 'https://online-study-f1d0e.web.app/',
    technology: [
      'React',
      'Node.JS',
      'Firebase',
      'Authentication',
      'Express Js',
      'Tailwind',
      'React Toastify',
      'React Icon',
      'Social Login',
    ],
    tag: '1 month ago',
  },
  {
    id: 8,
    image: projectImg,
    name: 'Dragon News',
    des: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id iure ullam ex commodi voluptas excepturi inventore molestias sint dignissimos ratione?',
    category: 'React',
    repo_link: 'https://github.com/DiptaPal/dragon-news-client',
    server_link: 'https://github.com/DiptaPal/dragon-news-server',
    live_link: 'https://dragon-news-24603.web.app/',
    technology: [
      'React',
      'Node.JS',
      'Firebase',
      'Authentication',
      'Express Js',
      'Bootstrap',
      'React Toastify',
      'React Icon',
      'Social Login',
    ],
    tag: '2 month ago',
  },
  {
    id: 9,
    image: projectImg,
    name: 'QuizPro',
    des: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id iure ullam ex commodi voluptas excepturi inventore molestias sint dignissimos ratione?',
    category: 'React',
    repo_link: 'https://github.com/DiptaPal/quiz-pro',
    live_link: 'https://quiz-pro-online.netlify.app/',
    technology: ['React', 'Tialwind CSS', 'React Toastify', 'API', 'Rechart'],
    tag: '3 month ago',
  },
  {
    id: 10,
    image: projectImg,
    name: 'Authen Tech',
    des: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id iure ullam ex commodi voluptas excepturi inventore molestias sint dignissimos ratione?',
    category: 'React',
    repo_link: 'https://github.com/DiptaPal/authen-tech',
    live_link: 'https://authentech-9cd3a.web.app/',
    technology: [
      'React',
      'Firebase Authentication',
      'Tialwind CSS',
      'React Toastify',
      'API',
      'Rechart'
    ],
    tag: '2 month ago',
  },
  // {
  //   id: 8,
  //   image: Project8,
  //   name: 'Panda Ecommerce',
  //   des: 'This is a Panda Ecommerce web application where user can manage his/her product which is more interesting as well as give',
  //   category: 'UI/UX design',
  //   repo_link: 'https://github.com/DiptaPal/panda-commerce',
  //   live_link: 'https://diptapal.github.io/panda-commerce/',
  //   technology: ['HTML', 'CSS', 'Bootstrap'],
  //   tag: '2 Years ago',
  // },
  // {
  //   id: 9,
  //   image: Project9,
  //   name: 'Hot Gadget',
  //   des: 'This is a Hot Gadget web application where user can manage his/her car product which is more interesting as well as give',
  //   category: 'UI/UX design',
  //   repo_link: 'https://github.com/NH-Rifat/Hot-gadget-using-bootstrap',
  //   live_link: 'https://hot-gadgeted.netlify.app',
  //   technology: ['HTML', 'CSS', 'Bootstrap'],
  //   tag: '2 Years ago',
  // },
];